version: '3.9'
 
services:
#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    container_name: database
#    environment:
#      MYSQL_ROOT_PASSWORD: ${db_root_password}
#      MYSQL_DATABASE: ${db_database}
#      MYSQL_USER: ${db_user}
#      MYSQL_PASSWORD: ${db_password}
#    ports:
#      - ${db_ports}
#    volumes:
#      - ./database/data:/var/lib/mysql
  scrapper:
    build:
      context: scrapper
      dockerfile: Dockerfile
    container_name: scrapper

networks:
  default:
    external:
      name: immoscrapper