version: '3.9'
 
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${db_root_password}
      MYSQL_DATABASE: ${db_database}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}
    ports:
      - ${db_ports}
    volumes:
      - ./database/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${db_user}
      PMA_PASSWORD: ${db_password}
    ports:
      - "8080:80"
#  scrapper:
#    build:
#      context: scrapper
#      dockerfile: Dockerfile
#    container_name: scrapper

networks:
  default:
    external:
      name: immoscrapper