CREATE TABLE IF NOT EXISTS properties (
    property_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    extraction_date DATE NOT NULL,
    url VARCHAR(255) NOT NULL,
    portal VARCHAR(30) NOT NULL,
    price INT,
    location VARCHAR(150),
    energy_certificate VARCHAR(1),
    built_up_area SMALLINT,
    usable_floor_area SMALLINT,
    floor_area SMALLINT,
    n_rooms TINYINT,
    n_bathrooms TINYINT,
    flooring VARCHAR(40),
    floor TINYINT,
    antiquity VARCHAR(50),
    `condition` VARCHAR(50),
    heating VARCHAR(50),
    equipped_kitchen BOOLEAN DEFAULT FALSE,
    lift BOOLEAN DEFAULT FALSE,
    air_conditioning VARCHAR(50),
    garage TINYINT,
    own_balcony BOOLEAN DEFAULT FALSE,
    terrace BOOLEAN DEFAULT FALSE,
    security_system BOOLEAN DEFAULT FALSE,
    facing VARCHAR(20),
    swimming_pool VARCHAR(30),
    garden VARCHAR(30)
) ENGINE=INNODB;